### PR TITLE
Change SourceDeductionService class in the Refund observer

### PR DESCRIPTION
**Pull request by markfischmann**
Change a class in the refund observer to use the module's own SourceDeductionService instead of the native one.
This causes refunds to not change stock status in cataloginventory_stock_item, cataloginventory_stock_status and inventory_source_item if the product goes from "out of stock" to "in stock" following a refund.

Instead of using the `vendor/ampersand/magento2-disable-stock-reservation/src/Model/SourceDeductionService/PatchedSourceDeductionService.php` class, it used the `vendor/magento/module-inventory-source-deduction-api/Model/SourceDeductionService.php` class.

### CODE REVIEW

**Comment by zeeshantpp** [comment]
@convenient @markfischmann  can we also review and merge this please?

**Comment by convenient** [comment]
Hey @markfischmann is it expected that this does not work unless it is paired with #93 ?

I've pushed a test and we can see in the 2.4.3 instance and higher we're still getting
```
1) CheckoutCest: Product goes back in stock when order is refunded
 Test  tests/acceptance/CheckoutCest.php:productGoesBackInStockWhenOrderIsRefunded
 Step  Assert equals 1,0,"Product did not go to is_in_stock=1 after a refund"
 Fail  Product did not go to is_in_stock=1 after a refund
Failed asserting that 0 matches expected 1.
```

I've created a PR and branch which combines #92 and #93 and we can see that 2.4.5 and higher are going green with the combination.

This testing infra is new, so there may be some bug or issue i've not gotten to the bottom of yet, but just thought i'd check first.

**Comment by markfischmann** [comment]
@convenient 
To be completely honest, I can't remember exactly, but on our production website running 2.4.3-p1 and recently 2.4.3-p3, there have not been any issues with both PRs working together.

I made two seperate PRs because there were two seperate issues, but I need them both to have a working system, so I guess we can say that they should be combined.

**Comment by convenient** [comment]
Thanks @markfischmann  Hmmm very strange that the combined tests are only passing for 2.4.5 and higher, would prefer to continue to support 2.4.3 if at all possible.

I'll give this a go through the code in xdebug I guess and see why `Product did not go to is_in_stock=1 after a refund` is still occurring :/ seeing as you say you needed it in 2.4.3 to get it working.

Did you do any other customisations that may need included do you think?

**Comment by markfischmann** [comment]
@convenient I wonder if it's not due to the fact that you're using the Refund API, which might possibly be different than the Credit Memo refund thing.
I'll try it out during the day when I have a bit of spare time and I'll get back to you when I have more information.

**Comment by convenient** [comment]
thanks @markfischmann that may be the case :) using the API for tests for ease of writing them

**Comment by convenient** [comment]
I did not mean to close these as invalid, apologies I made an error, I'm continuing the work in https://github.com/AmpersandHQ/magento2-disable-stock-reservation/pull/107 thanks

**Comment by convenient** [comment]
Hello @markfischmann 

I am closing this PR and have cherry picked the relevant commits into https://github.com/AmpersandHQ/magento2-disable-stock-reservation/releases/tag/1.2.9

In https://github.com/AmpersandHQ/magento2-disable-stock-reservation/pull/120 I was able to reproduce your bug on the affected version of Magento, but the only change necessary to correct the `is_in_stock` handling was the interface fix, I didnt need any of the `DecrementQtyForMultipleSourceItem` fixes.

Please read through the notes on https://github.com/AmpersandHQ/magento2-disable-stock-reservation/pull/120, I tested
- rest api
- adminhtml controller
- manually

Your fix to the interface definitely fixed the issue, but i couldnt see any other problems which necessitated `DecrementQtyForMultipleSourceItem`.

There's a lot more test infra and coverage now, so maybe if you can point out any other requirement to replicate this issue in your case I can try and repro but based on my testing, this issue is resolved.

Thanks for much for your patience on this, with all the varying versions of Magento we're trying to support with this module it's a bit tricky to ensure the change is appropriate, and that we have the necessary test coverage.

If you have any more details please raise a new issue and thanks for your contribution.

**Pull request closed without merging**
